x-env-files: &env_files
  - path: ./../../.env.dev
    required: true
  - path: ./../../.env.shared
    required: true
  - path: ./../../.env.local
    required: false
  - path: ./../../.env
    required: false

services:
  bismillahdao-raqib:
    build:
      dockerfile: ./docker/images/Dockerfile.raqib-dev
      context: ./../../../
    container_name: bismillahdao-raqib
    develop:
      watch:
        - action: sync
          path: ./../../../muhafidh/src
          target: /app/muhafidh/src
          ignore:
            - ./../../../muhafidh/target/
        - action: sync
          path: ./../../../muhafidh/Cargo.toml
          target: /app/muhafidh/Cargo.toml
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - muhafidh_cargo_cache:/usr/local/cargo/registry
      - muhafidh_sccache:/sccache
      - muhafidh_target_cache:/app/muhafidh/target
    restart: unless-stopped
    env_file: *env_files
    networks:
      - bismillahdao_net

volumes:
  muhafidh_cargo_cache:
  muhafidh_target_cache:
  muhafidh_sccache: