# Build the frontend using rollup
FROM rust:1.82-bullseye AS base

# install base packages
RUN apt-get clean \
    && apt-get update --fix-missing \
    && apt-get install -y \
    git \
    curl \
    gcc \
    g++ \
    build-essential \
    libssl-dev \
    pkg-config \
    libz-dev \
    wget \
    curl \
    python3 \
    ccze \
    && curl -fsSL https://deb.nodesource.com/setup_23.x | bash \
    && apt-get install -y nodejs 

# install justfile
RUN cargo install just watchexec-cli

WORKDIR /app
COPY twitter-monitor /app/twitter-monitor
COPY justfile /app/justfile

# install backend dependencies
WORKDIR /app/twitter-monitor
RUN cargo build

CMD ["watchexec", "-i", "./**/target", "-w", "src", "-w", "config", "-e", "rs","--project-origin", ".", "-r", "just", "run"]

# CMD ["just", "run"]  