# Build the frontend using rollup
FROM rust:1.82-bullseye AS base

# install base packages
RUN apt-get clean \
    && apt-get update --fix-missing \
    && apt-get install -y \
    git \
    curl \
    gcc \
    g++ \
    build-essential \
    wget \
    curl \
    python3 \
    ccze \
    && curl -fsSL https://deb.nodesource.com/setup_23.x | bash \
    && apt-get install -y nodejs 
RUN rustup target add wasm32-unknown-unknown

# install justfile
RUN cargo install just watchexec-cli

WORKDIR /app
COPY backend /app/backend
COPY justfile /app/justfile
COPY frontend /app/frontend

# Install frontend dependencies
WORKDIR /app/frontend
RUN npm install

# install backend dependencies
WORKDIR /app/backend
RUN cargo build --features dev

# Create a non-root user
RUN groupadd -r rizilab && useradd -r -g rizilab -d /app rizilab

WORKDIR /app

# Change ownership of the application files
RUN chown -R rizilab:rizilab /app
RUN chown -R rizilab:rizilab /usr/local/cargo

FROM base

ENV XDG_CACHE_HOME=/app/.cache
USER rizilab

CMD ["watchexec", "-i", "./**/target", "-i", "frontend/node_modules", "-i", "frontend/devhtml/js", "-i", "frontend/devhtml/css", "-w", "frontend/src", "-w", "backend/src", "-e", "html,js,rs,json","--project-origin", ".", "-r", "just", "all"]
