FROM caddy:2.9.1-builder-alpine AS builder
 
RUN xcaddy build \
    --with github.com/mholt/caddy-ratelimit \
    --with github.com/caddy-dns/cloudflare \
    --with github.com/mholt/caddy-l4 \
    --with github.com/WeidiDeng/caddy-cloudflare-ip \
    --with github.com/porech/caddy-maxmind-geolocation \
    --with github.com/caddyserver/transform-encoder \
    --with github.com/hslatman/caddy-crowdsec-bouncer/http \
    --with github.com/lucaslorentz/caddy-docker-proxy/v2@=github.com/rizary/caddy-docker-proxy/v2@v2.9.5 # fix for caddy 2.9.1 until upstream fix
 
FROM caddy:2.9.1-alpine
 
COPY --from=builder /usr/bin/caddy /usr/bin/caddy