[storage_db]
user = ""
password = ""
port = ""
host = ""
pool_size = 0
db_name = ""

[storage_db.tls]
cert_path = ""
key_path = ""
ca_path = ""

[storage_redis]
user = ""

[rpc]
http_url = ""
ws_url = ""
api_key = ""

[logging]
# Set log directory (default: .logs)
# Three separate directories will be created:
# - .logs/ - for INFO level logs
# - .logs/debug/ - for DEBUG level logs
# - .logs/error/ - for WARN and ERROR level logs
directory = ".logs"