default:
  @just --list

# Run the PumpFun token raqib with WebSocket (default)
run-raqib:
  cargo run --release --bin raqib

# Build the PumpFun raqib
build-raqib:
  cargo build --bin raqib

# Build a release version
release-raqib:
  cargo build --release --bin raqib

# Run tests
test-raqib:
  cargo test --bin raqib

# Clean the build artifacts
clean:
  cargo clean

# Check the code for errors
check:
  cargo check