array_width                     = 80
binop_separator                 = "Front"
brace_style                     = "PreferSameLine"
chain_width                     = 80
color                           = "Never"
combine_control_expr            = false
empty_item_single_line          = false
comment_width                   = 120
control_brace_style             = "AlwaysSameLine"
edition                         = "2024"
enum_discrim_align_threshold    = 40
error_on_line_overflow          = true
error_on_unformatted            = true
fn_params_layout                = "Vertical"
fn_single_line                  = true
condense_wildcard_suffixes      = true
force_multiline_blocks          = true
format_code_in_doc_comments     = true
format_macro_matchers           = true
format_strings                  = true
match_block_trailing_comma      = true
max_width                       = 120
merge_derives                   = false
imports_granularity             = "Item"
normalize_comments              = true
normalize_doc_attributes        = true
overflow_delimited_expr         = true
reorder_impl_items              = true
reorder_imports                 = true
group_imports                   = "StdExternalCrate"
single_line_let_else_max_width  = 0
struct_field_align_threshold    = 80
struct_lit_single_line          = true
struct_lit_width                = 40
style_edition                   = "2021"
tab_spaces                      = 2
use_field_init_shorthand        = true
use_small_heuristics            = "Off"
wrap_comments                   = true